/**
 * Resolved paths for the static fixture sets shipped by `@podkit/test-fixtures`.
 *
 * Consumers should never hard-code paths to fixtures from the repo root. Use
 * the accessors here so the location is owned by this package and survives
 * future moves.
 *
 * The package root is discovered at runtime by walking up from this file's
 * location and looking for the `@podkit/test-fixtures` package.json. This
 * works for both the source path (test-packages/test-fixtures/src/static/) and
 * the bundled `dist/lib.js` output.
 *
 * @module
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PACKAGE_NAME = '@podkit/test-fixtures';

let cachedRoot: string | null = null;

/**
 * Locate the test-fixtures package root by walking up from the current file
 * looking for a `package.json` whose `name` matches.
 *
 * The result is cached so the directory walk runs at most once per process.
 */
function findPackageRoot(): string {
  if (cachedRoot !== null) return cachedRoot;

  let dir = dirname(fileURLToPath(import.meta.url));
  // Hard cap on walk depth to avoid infinite loops on broken filesystems.
  for (let i = 0; i < 16; i++) {
    const pkgPath = join(dir, 'package.json');
    if (existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as { name?: string };
        if (pkg.name === PACKAGE_NAME) {
          cachedRoot = dir;
          return dir;
        }
      } catch {
        // unparseable package.json — keep walking
      }
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }

  throw new Error(
    `Could not locate ${PACKAGE_NAME} package root by walking up from ${dirname(
      fileURLToPath(import.meta.url)
    )}`
  );
}

/**
 * Absolute path to the package-owned `fixtures/` directory.
 *
 * Outputs of the static generators land here. The directory is gitignored
 * and regenerated on demand via the `generate-static-fixtures` script.
 */
export function getStaticFixturesRoot(): string {
  return join(findPackageRoot(), 'fixtures');
}

/**
 * Path to the multi-format audio fixture set.
 *
 * Contents (regenerated by `generate-static-fixtures --only multi-format`):
 * 01-wav-track.wav, 02-aiff-track.aiff, 03-flac-track.flac,
 * 04-alac-track.m4a, 05-mp3-track.mp3, 06-aac-track.m4a,
 * 07-ogg-track.ogg, 08-opus-track.opus
 */
export function getMultiFormatFixturesDir(): string {
  return join(getStaticFixturesRoot(), 'audio', 'multi-format');
}

/**
 * Path to the multi-format set with embedded artwork (scenario B).
 *
 * Same 8 tracks as `multi-format`, each with a `cover.jpg` embedded via the
 * codec's native attached-picture mechanism.
 */
export function getMultiFormatEmbeddedFixturesDir(): string {
  return join(getStaticFixturesRoot(), 'audio', 'multi-format-embedded');
}

/**
 * Path to the multi-format set with a sidecar cover only (scenario C).
 *
 * Same 8 tracks as `multi-format`, plus a `cover.jpg` next to them. The audio
 * files themselves carry no embedded artwork.
 */
export function getMultiFormatSidecarFixturesDir(): string {
  return join(getStaticFixturesRoot(), 'audio', 'multi-format-sidecar');
}

/**
 * Path to the multi-format set with both embedded artwork and a sidecar
 * cover (scenario D).
 */
export function getMultiFormatBothFixturesDir(): string {
  return join(getStaticFixturesRoot(), 'audio', 'multi-format-both');
}

/**
 * Path to the multi-format-embedded *alternative* set — identical metadata
 * to {@link getMultiFormatEmbeddedFixturesDir} but with a different cover
 * colour. Artwork-change tests swap files between the two variants to
 * mutate the source artwork bytes without disturbing the track's match key.
 */
export function getMultiFormatEmbeddedAltFixturesDir(): string {
  return join(getStaticFixturesRoot(), 'audio', 'multi-format-embedded-alt');
}

/**
 * Path to the multi-format-embedded *stripped* set — identical metadata to
 * {@link getMultiFormatEmbeddedFixturesDir} but with no embedded artwork.
 * The artwork-change matrix swaps embedded → stripped to model the source
 * losing its cover without disturbing the track's match key.
 */
export function getMultiFormatEmbeddedStrippedFixturesDir(): string {
  return join(getStaticFixturesRoot(), 'audio', 'multi-format-embedded-stripped');
}

/**
 * Path to the multi-format set with a high-resolution (1024px) embedded cover —
 * same tracks as the embedded variant but a cover larger than any device's
 * `artworkMaxResolution`, so the resize matrix can observe a real downscale.
 */
export function getMultiFormatEmbeddedHiresFixturesDir(): string {
  return join(getStaticFixturesRoot(), 'audio', 'multi-format-embedded-hires');
}

/**
 * Path to the multi-format *compilation* set — the 8 tracks as a various-artist
 * album: distinct per-track artist, shared album / album_artist / compilation
 * flag, art embedded only in the embed-capable anchors. Exercises the album
 * artwork cache's `(artist, album)` keying.
 */
export function getMultiFormatCompilationFixturesDir(): string {
  return join(getStaticFixturesRoot(), 'audio', 'multi-format-compilation');
}

/**
 * Path to the goldberg-selections fixture set.
 *
 * Contents: 01-harmony.flac, 02-vibrato.flac, 03-tremolo.flac, cover.jpg
 */
export function getGoldbergFixturesDir(): string {
  return join(getStaticFixturesRoot(), 'audio', 'goldberg-selections');
}

/**
 * Path to the synthetic-tests fixture set.
 *
 * Contents: 01-a440.flac, 02-sweep.flac, 03-dual-tone.flac (no artwork),
 * cover.jpg
 */
export function getSyntheticTestsFixturesDir(): string {
  return join(getStaticFixturesRoot(), 'audio', 'synthetic-tests');
}

/**
 * Path to the video fixture set.
 *
 * Contents: compatible-h264.mp4, low-quality.mp4, high-res-h264.mkv,
 * incompatible-vp9.webm, movie-with-metadata.mp4, tvshow-episode.mp4
 */
export function getVideoFixturesDir(): string {
  return join(getStaticFixturesRoot(), 'video');
}

/**
 * Names of the static fixture sets, used by `ensureFixturesExist` and by
 * `scripts/generate-static-fixtures.ts --only <set>`.
 */
export type StaticFixtureSet =
  | 'multi-format'
  | 'multi-format-embedded'
  | 'multi-format-embedded-alt'
  | 'multi-format-embedded-stripped'
  | 'multi-format-embedded-hires'
  | 'multi-format-compilation'
  | 'multi-format-sidecar'
  | 'multi-format-both'
  | 'goldberg-selections'
  | 'synthetic-tests'
  | 'video';

/**
 * Lookup table from set name to absolute directory.
 */
const SET_DIR: Record<StaticFixtureSet, () => string> = {
  'multi-format': getMultiFormatFixturesDir,
  'multi-format-embedded': getMultiFormatEmbeddedFixturesDir,
  'multi-format-embedded-alt': getMultiFormatEmbeddedAltFixturesDir,
  'multi-format-embedded-stripped': getMultiFormatEmbeddedStrippedFixturesDir,
  'multi-format-embedded-hires': getMultiFormatEmbeddedHiresFixturesDir,
  'multi-format-compilation': getMultiFormatCompilationFixturesDir,
  'multi-format-sidecar': getMultiFormatSidecarFixturesDir,
  'multi-format-both': getMultiFormatBothFixturesDir,
  'goldberg-selections': getGoldbergFixturesDir,
  'synthetic-tests': getSyntheticTestsFixturesDir,
  video: getVideoFixturesDir,
};

/**
 * Sentinel file written by each generator after every track has been
 * produced. `ensureFixturesExist` checks for this rather than any
 * individual fixture file, so a partial output (e.g. ffmpeg crash mid-run)
 * leaves the sentinel absent and the next preflight fails loudly.
 *
 * The file itself is written by `writeGeneratedSentinel` in `shared.ts`
 * and is the last line of each generator function.
 */
const SENTINEL_FILENAME = '.generated';

/**
 * Throw with an actionable message if the named fixture set has not been
 * generated yet.
 *
 * Tests that depend on a static fixture should call this at module load:
 *
 * ```ts
 * import { ensureFixturesExist } from '@podkit/test-fixtures';
 * ensureFixturesExist('multi-format');
 * ```
 *
 * Turbo runs `generate-static-fixtures` automatically as a `test:integration`
 * dependency, so the check is normally a no-op. It only fires when a test is
 * run outside the turbo graph (e.g. `bun test path/to/file.test.ts` directly)
 * against a clean checkout.
 */
export function ensureFixturesExist(set: StaticFixtureSet): void {
  const dir = SET_DIR[set]();
  const sentinel = join(dir, SENTINEL_FILENAME);
  if (!existsSync(sentinel)) {
    throw new Error(
      `Test fixture set '${set}' is missing or incomplete at ${dir}.\n` +
        `Run \`bun run --filter @podkit/test-fixtures generate-static-fixtures\` to (re)generate it.`
    );
  }
}
