import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import type { IpodModelNumber } from './types';

/**
 * Models with pre-built templates. createTestIpod uses fs.cp to copy a template
 * (~5ms) instead of spawning gpod-tool init (~300ms) when the requested model
 * is in this list and no overrides force the slow path.
 *
 * Templates are generated by `bun run generate-templates` (turbo-cached).
 * Add a model here and rerun the task to extend coverage.
 */
export const TEMPLATE_MODELS: readonly IpodModelNumber[] = [
  'MA147', // iPod Video 60GB (5th gen)
  'MA002', // iPod Video 30GB (5th gen)
  'MA146', // iPod Video 30GB Black (5th gen)
  'MA477', // iPod Nano 2GB (2nd gen)
  'MB565', // iPod Classic 120GB (6th gen) — hash58
  'MC293', // iPod Classic 160GB (7th gen) — hash58
  'MC027', // iPod Nano 8GB (5th gen) — hash72 + HashInfo
] as const;

/**
 * Absolute path to the templates root directory.
 *
 * Resolved relative to this module so it works whether invoked from `src/`
 * (during dev/tests) or from the bundled `dist/index.js` (when imported by
 * consumer packages via the workspace symlink).
 */
export function templatesDir(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), '..', 'templates');
}

export function templatePath(model: IpodModelNumber): string {
  return resolve(templatesDir(), model);
}
