import type { GenerationInfo } from './types';

/**
 * Per-generation summary data.
 *
 * One entry per supported iPod generation, with all known model numbers
 * and the generation's overall confidence level.
 */
export const GENERATION_INFO: GenerationInfo[] = [
  {
    generation: 'first',
    displayName: 'iPod (1st Gen)',
    models: ['M8513', 'M8541'],
    features: { music: true, artwork: false, video: false, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
  {
    generation: 'second',
    displayName: 'iPod (2nd Gen)',
    models: ['M8737', 'M8740', 'M8738', 'M8741'],
    features: { music: true, artwork: false, video: false, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
  {
    generation: 'third',
    displayName: 'iPod (3rd Gen)',
    models: ['M8976', 'M8946', 'M9244', 'M9245', 'M9460'],
    features: { music: true, artwork: false, video: false, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
  {
    generation: 'fourth',
    displayName: 'iPod (4th Gen)',
    models: ['M9282', 'M9268', 'M9787', 'M9788'],
    features: { music: true, artwork: false, video: false, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
  {
    generation: 'photo',
    displayName: 'iPod Photo',
    models: ['MA079', 'M9828', 'M9829'],
    features: { music: true, artwork: true, video: false, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
  {
    generation: 'video_1',
    displayName: 'iPod Video (5th Gen)',
    models: ['MA002', 'MA003', 'MA146', 'MA147'],
    features: { music: true, artwork: true, video: true, playlists: true },
    checksumType: 'none',
    confidence: 'verified',
  },
  {
    generation: 'video_2',
    displayName: 'iPod Video (5.5th Gen)',
    models: ['MA444', 'MA446', 'MA448', 'MA450'],
    features: { music: true, artwork: true, video: true, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
  {
    generation: 'classic_1',
    displayName: 'iPod Classic (6th Gen, 80GB)',
    models: ['MB029', 'MB147', 'MB150'],
    features: { music: true, artwork: true, video: true, playlists: true },
    checksumType: 'hash58',
    confidence: 'simulated',
  },
  {
    generation: 'classic_2',
    displayName: 'iPod Classic (6th Gen, 120GB)',
    models: ['MB565'],
    features: { music: true, artwork: true, video: true, playlists: true },
    checksumType: 'hash58',
    confidence: 'simulated',
  },
  {
    generation: 'classic_3',
    displayName: 'iPod Classic (7th Gen)',
    models: ['MC293', 'MC297'],
    features: { music: true, artwork: true, video: true, playlists: true },
    checksumType: 'hash58',
    confidence: 'simulated',
  },
  {
    generation: 'nano_1',
    displayName: 'iPod Nano (1st Gen)',
    models: ['MA004', 'MA005', 'MA099', 'MA107', 'MA350', 'MA352'],
    features: { music: true, artwork: true, video: false, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
  {
    generation: 'nano_2',
    displayName: 'iPod Nano (2nd Gen)',
    models: ['MA477', 'MA478', 'MA426', 'MA427', 'MA428'],
    features: { music: true, artwork: true, video: false, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
  {
    generation: 'nano_3',
    displayName: 'iPod Nano (3rd Gen)',
    models: ['MA978', 'MA980', 'MB245', 'MB249', 'MB261'],
    features: { music: true, artwork: true, video: true, playlists: true },
    checksumType: 'hash58',
    confidence: 'simulated',
  },
  {
    generation: 'nano_4',
    displayName: 'iPod Nano (4th Gen)',
    models: ['MB598', 'MB654', 'MB732', 'MB903', 'MB909', 'MB911', 'MB913', 'MB915', 'MB918'],
    features: { music: true, artwork: true, video: true, playlists: true },
    checksumType: 'hash58',
    confidence: 'simulated',
  },
  {
    generation: 'nano_5',
    displayName: 'iPod Nano (5th Gen)',
    models: ['MC027', 'MC031', 'MC040', 'MC049', 'MC050', 'MC051', 'MC054', 'MC062', 'MC064', 'MC066', 'MC068', 'MC075'],
    features: { music: true, artwork: true, video: true, playlists: true },
    checksumType: 'hash72',
    confidence: 'simulated',
  },
  {
    generation: 'mini_1',
    displayName: 'iPod Mini (1st Gen)',
    models: ['M9160', 'M9436', 'M9435', 'M9434', 'M9437'],
    features: { music: true, artwork: false, video: false, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
  {
    generation: 'mini_2',
    displayName: 'iPod Mini (2nd Gen)',
    models: ['M9800', 'M9801', 'M9802', 'M9803', 'M9804', 'M9805', 'M9806', 'M9807'],
    features: { music: true, artwork: false, video: false, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
  {
    generation: 'shuffle_1',
    displayName: 'iPod Shuffle (1st Gen)',
    models: ['M9724', 'M9725', 'MA133'],
    features: { music: true, artwork: false, video: false, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
  {
    generation: 'shuffle_2',
    displayName: 'iPod Shuffle (2nd Gen)',
    models: ['MA546', 'MA564', 'MA565', 'MA947', 'MA948', 'MA949', 'MA950', 'MA951', 'MB225', 'MB226', 'MB227', 'MB228', 'MB229', 'MB518', 'MB519', 'MB520', 'MB522', 'MB523'],
    features: { music: true, artwork: false, video: false, playlists: true },
    checksumType: 'none',
    confidence: 'simulated',
  },
];
