/**
 * Error codes emitted by `podkit device` (and all subcommands).
 *
 * Exhaustive — every CliError thrown from this command's runners uses one
 * of these. Consumers branching on `output.code` can rely on this union.
 */
export const DeviceErrorCodes = {
  // Device resolution / I/O
  DEVICE_NOT_RESOLVED: 'DEVICE_NOT_RESOLVED',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_PATH_UNRESOLVED: 'DEVICE_PATH_UNRESOLVED',
  DEVICE_PATH_NOT_FOUND: 'DEVICE_PATH_NOT_FOUND',
  DEVICE_REQUIRED: 'DEVICE_REQUIRED',
  NO_DEVICE: 'NO_DEVICE',
  CORE_LOAD_FAILED: 'CORE_LOAD_FAILED',
  CONFIG_SAVE_FAILED: 'CONFIG_SAVE_FAILED',
  CANCELLED: 'CANCELLED',
  // Add / set / remove
  UNSUPPORTED_FILESYSTEM_ON_LINUX: 'UNSUPPORTED_FILESYSTEM_ON_LINUX',
  VOLUME_UUID_REQUIRED: 'VOLUME_UUID_REQUIRED',
  INVALID_DEVICE_NAME: 'INVALID_DEVICE_NAME',
  DEVICE_EXISTS: 'DEVICE_EXISTS',
  DEVICE_ARG_CONFLICT: 'DEVICE_ARG_CONFLICT',
  INVALID_QUALITY: 'INVALID_QUALITY',
  INVALID_AUDIO_QUALITY: 'INVALID_AUDIO_QUALITY',
  INVALID_VIDEO_QUALITY: 'INVALID_VIDEO_QUALITY',
  INVALID_ENCODING: 'INVALID_ENCODING',
  PATH_REQUIRED: 'PATH_REQUIRED',
  PATH_NOT_FOUND: 'PATH_NOT_FOUND',
  PATH_NOT_DIRECTORY: 'PATH_NOT_DIRECTORY',
  INVALID_ARTWORK_RESOLUTION: 'INVALID_ARTWORK_RESOLUTION',
  INVALID_ARTWORK_SOURCE: 'INVALID_ARTWORK_SOURCE',
  INVALID_AUDIO_CODEC: 'INVALID_AUDIO_CODEC',
  INVALID_OPTION_FOR_TYPE: 'INVALID_OPTION_FOR_TYPE',
  UNSUPPORTED_DEVICE: 'UNSUPPORTED_DEVICE',
  /** Verify-tier cross-check: on-disk SysInfo disagrees with the live device. */
  IDENTITY_MISMATCH: 'IDENTITY_MISMATCH',
  EMPTY_IDENTITY: 'EMPTY_IDENTITY',
  INIT_FAILED: 'INIT_FAILED',
  NO_UPDATES: 'NO_UPDATES',
  // Scan
  SCAN_UNSUPPORTED: 'SCAN_UNSUPPORTED',
  NO_IPOD: 'NO_IPOD',
  DETECTED_MASS_STORAGE: 'DETECTED_MASS_STORAGE',
  MULTIPLE_IPODS: 'MULTIPLE_IPODS',
  // Mount
  MOUNT_UNSUPPORTED: 'MOUNT_UNSUPPORTED',
  MOUNT_REQUIRES_SUDO: 'MOUNT_REQUIRES_SUDO',
  MOUNT_FAILED: 'MOUNT_FAILED',
  // Eject
  EJECT_UNSUPPORTED: 'EJECT_UNSUPPORTED',
  EJECT_FAILED: 'EJECT_FAILED',
  // Init lifecycle
  DEVICE_ALREADY_INITIALIZED: 'DEVICE_ALREADY_INITIALIZED',
  NEEDS_FORMAT: 'NEEDS_FORMAT',
  NEEDS_PARTITION: 'NEEDS_PARTITION',
  NEEDS_REPAIR: 'NEEDS_REPAIR',
  HARDWARE_ERROR: 'HARDWARE_ERROR',
  DATABASE_EXISTS: 'DATABASE_EXISTS',
  // Content (clear / reset / list)
  IPOD_ONLY: 'IPOD_ONLY',
  IPOD_DATABASE_OPEN_FAILED: 'IPOD_DATABASE_OPEN_FAILED',
  IPOD_DATABASE_INVALID: 'IPOD_DATABASE_INVALID',
  INVALID_TYPE: 'INVALID_TYPE',
  RESET_FAILED: 'RESET_FAILED',
  RESET_ARTWORK_FAILED: 'RESET_ARTWORK_FAILED',
  // Music / video listing
  INVALID_OPTION: 'INVALID_OPTION',
  INVALID_FIELDS: 'INVALID_FIELDS',
  MUSIC_LIST_FAILED: 'MUSIC_LIST_FAILED',
  VIDEO_LIST_FAILED: 'VIDEO_LIST_FAILED',
  // Archive
  ARCHIVE_DUMP_FAILED: 'ARCHIVE_DUMP_FAILED',
  ARCHIVE_TRANSFORM_FAILED: 'ARCHIVE_TRANSFORM_FAILED',
  /** Auto-detect found no iPod and no other device on a supported platform. */
  NO_DEVICE_FOUND: 'NO_DEVICE_FOUND',
  /** Auto-detect found an iPod, but it has no mounted volume. */
  IPOD_NOT_MOUNTED: 'IPOD_NOT_MOUNTED',
} as const;

export type DeviceErrorCode = (typeof DeviceErrorCodes)[keyof typeof DeviceErrorCodes];
