/**
 * `podkit device scan` — scan for connected devices.
 */
import { Command } from 'commander';
import { confirm } from '../../utils/confirm.js';
import { getContext } from '../../context.js';
import { runAction } from '../../errors.js';
import { loadCoreOrFail, type CoreLoaderDeps } from '../../handler-deps.js';
import { OutputContext, formatBytes, formatNumber, bold } from '../../output/index.js';
import type { DeviceConfig } from '../../config/index.js';
import type { ReadinessResult, ReadinessUnsupportedReason } from '@podkit/core';
import { STAGE_DISPLAY_NAMES } from '@podkit/core';
import { stageMarker, formatReadinessLevel } from '../readiness-display.js';
import {
  renderDeviceScan,
  type DeviceScanInput,
  type DeviceScanIpodRow,
} from '../device-scan-render.js';
import { DeviceErrorCodes } from './error-codes.js';
import {
  findUndetectedDevices,
  findConfiguredDeviceName,
  redactPaths,
  formatIFlashMountExplanation,
} from './shared.js';
import type { DeviceScanOutput, DeviceScanSuccess } from './output-types.js';

type DeviceScanDeviceEntry = NonNullable<DeviceScanSuccess['devices']>[number];

/**
 * Generate a diagnostic report for troubleshooting.
 */
async function generateDiagnosticReport(
  ipods: Array<{
    volumeName: string;
    volumeUuid: string;
    identifier: string;
    size: number;
    isMounted: boolean;
    mountPoint?: string;
  }>,
  readinessResults: ReadinessResult[],
  usbOnlyIpods: Array<{
    modelName?: string;
    supported?: boolean;
    unsupportedReason?: ReadinessUnsupportedReason;
  }>,
  recognisedMassStorage: Array<{ presetId: string; diskIdentifier?: string }>,
  configuredDevices: Array<{ name: string; type: string; path?: string }>,
  config: { devices?: Record<string, DeviceConfig> },
  version: string
): Promise<string> {
  const { release } = await import('node:os');
  const lines: string[] = [];

  lines.push('podkit diagnostic report');
  lines.push('========================');
  lines.push('');

  // System info
  lines.push('System:');
  lines.push(`  podkit version: ${version}`);
  const platformName =
    process.platform === 'darwin'
      ? `darwin (macOS ${release()})`
      : `${process.platform} (${release()})`;
  lines.push(`  Platform: ${platformName}`);
  lines.push(`  Node.js: ${process.version}`);
  lines.push('');

  const hasAnyDevices =
    ipods.length > 0 ||
    usbOnlyIpods.length > 0 ||
    recognisedMassStorage.length > 0 ||
    configuredDevices.length > 0;

  if (!hasAnyDevices) {
    lines.push('No devices found.');
    lines.push('');
    lines.push('---');
    lines.push('Generated by podkit device scan --report');
    return lines.join('\n');
  }

  lines.push('Devices:');

  // iPods with readiness
  for (let i = 0; i < ipods.length; i++) {
    if (i > 0) lines.push('---');
    const device = ipods[i]!;
    const readiness = readinessResults[i];
    const label = device.volumeName || '(unnamed)';
    const identifier = device.identifier ? ` (${device.identifier})` : '';

    lines.push(`  iPod: ${label}${identifier}`);

    // Config relationship
    const configName = findConfiguredDeviceName(device, config.devices ?? {});
    if (configName) {
      lines.push(`  Configured as: ${configName}`);
    } else {
      lines.push('  Not configured');
    }

    if (readiness) {
      lines.push('');
      lines.push('  Readiness:');
      for (const stage of readiness.stages) {
        const marker = stageMarker(stage.status);
        const name = STAGE_DISPLAY_NAMES[stage.stage] || stage.stage;
        let line = `    ${marker} ${name}`;
        if (stage.summary) {
          line += ` — ${stage.summary}`;
        }
        lines.push(line);

        // Include error interpretation for failed stages
        if (stage.status === 'fail' && stage.details?.interpretation) {
          lines.push(`      ${stage.details.interpretation}`);
        }
      }

      lines.push('');

      // Summary line
      if (readiness.level === 'ready' && readiness.summary) {
        const trackStr = formatNumber(readiness.summary.trackCount);
        const parts = [`${trackStr} track${readiness.summary.trackCount === 1 ? '' : 's'}`];
        if (readiness.summary.freeBytes !== undefined) {
          parts.push(`${formatBytes(readiness.summary.freeBytes)} free`);
        }
        lines.push(`  Level: Ready — ${parts.join(', ')}`);
      } else {
        const cmdId = configName ?? device.mountPoint ?? label;
        lines.push(`  Level: ${formatReadinessLevel(readiness.level, cmdId)}`);
      }
    }

    lines.push('');
  }

  // USB-only iPods (recognised as iPods but with no mounted disk).
  for (const usbDevice of usbOnlyIpods) {
    lines.push('---');
    const label = usbDevice.modelName ?? 'Unknown iPod';
    lines.push(`  iPod: ${label} (USB only)`);
    if (!usbDevice.supported && usbDevice.unsupportedReason) {
      lines.push(`  ${usbDevice.unsupportedReason.headline}`);
    }
    lines.push('');
  }

  // Recognised mass-storage devices (Echo Mini etc.).
  for (const recognised of recognisedMassStorage) {
    lines.push('---');
    if (recognised.diskIdentifier) {
      lines.push(`  Mass-storage: ${recognised.presetId} — disk: ${recognised.diskIdentifier}`);
    } else {
      lines.push(`  Mass-storage: ${recognised.presetId} — no volume mounted`);
    }
    lines.push('');
  }

  // Configured devices not detected
  for (const cd of configuredDevices) {
    lines.push('---');
    const pathInfo = cd.path ? ` — ${cd.path}` : '';
    lines.push(`  ${cd.name} (${cd.type})${pathInfo} [not detected]`);
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by podkit device scan --report');
  return lines.join('\n');
}

interface DeviceScanOptions {
  mount?: boolean;
  report?: boolean;
}

/**
 * Dependency injection seam for `runDeviceScan`. Tests pass stubs to avoid
 * real USB walks and mount operations.
 */
export interface DeviceScanDeps extends CoreLoaderDeps {
  getDeviceManager?: () => import('@podkit/core').DeviceManager;
  confirm?: (msg: string) => Promise<boolean>;
}

export const scanSubcommand = new Command('scan')
  .description('scan for connected devices')
  .option('--mount', 'automatically mount unmounted devices')
  .option('--report', 'output diagnostic report for troubleshooting')
  .action(async (scanOptions: DeviceScanOptions) => {
    const { globalOpts } = getContext();
    const out = OutputContext.fromGlobalOpts(globalOpts);
    const cliVersion = scanSubcommand.parent?.parent?.version() ?? 'unknown';
    await runAction(out, () => runDeviceScan(scanOptions, out, {}, cliVersion));
  });

export async function runDeviceScan(
  scanOptions: DeviceScanOptions,
  out: OutputContext,
  deps: DeviceScanDeps = {},
  cliVersion = 'unknown'
): Promise<void> {
  const { globalOpts, config } = getContext();
  const confirmFn = deps.confirm ?? confirm;

  const core = await loadCoreOrFail(deps, DeviceErrorCodes.CORE_LOAD_FAILED);
  const {
    checkReadiness,
    enumerateUsb,
    classifyUsbDevices,
    createUsbOnlyReadinessResult,
    reconcileIpodDiscovery,
  } = core;
  const manager = (deps.getDeviceManager ?? core.getDeviceManager)();

  // Enumerate the USB bus and classify the result. `enumerateUsb` returns
  // EVERY USB device on the bus (mice, hubs, docks, …); `classifyUsbDevices`
  // drops everything that is not a recognised iPod or mass-storage DAP, so
  // the rest of `device scan` only ever sees real music players.
  type RecognizedDevice = Awaited<ReturnType<typeof classifyUsbDevices>>[number];
  type IpodRecognized = Extract<RecognizedDevice, { kind: 'ipod' }>;
  type MassStorageRecognized = Extract<RecognizedDevice, { kind: 'mass-storage' }>;
  type UnsupportedRecognized = Extract<RecognizedDevice, { kind: 'unsupported' }>;

  let ipods: Awaited<ReturnType<typeof manager.findIpodDevices>> = [];
  let recognizedDevices: RecognizedDevice[] = [];
  if (manager.isSupported) {
    const [foundIpods, enumerated] = await Promise.all([manager.findIpodDevices(), enumerateUsb()]);
    ipods = foundIpods;
    recognizedDevices = classifyUsbDevices(enumerated);
  }

  // Split the classified-USB stream by kind. Only the iPod-shaped entries
  // feed into reconciliation against the block-device side; mass-storage
  // entries render as their own scan group, and vendor-recognised-but-rejected
  // entries surface as USB-only rows with `level: 'unsupported'`.
  const ipodRecognizedList = recognizedDevices.filter(
    (d): d is IpodRecognized => d.kind === 'ipod'
  );
  const massStorageList = recognizedDevices.filter(
    (d): d is MassStorageRecognized => d.kind === 'mass-storage'
  );
  // Vendor-recognised but no preset (Sony Walkman, …). Surfaced as USB-only
  // entries with `level: 'unsupported'` so the user gets a clear rejection
  // message instead of the device silently vanishing from the scan.
  const unsupportedRecognizedList = recognizedDevices.filter(
    (d): d is UnsupportedRecognized => d.kind === 'unsupported'
  );

  // Reconcile the two pipelines into one record per physical iPod. The
  // primitive is pure (no I/O, no platform branches) — block-side
  // `usbFingerprint` is populated by Linux's `findIpodDevices` from sysfs,
  // USB-side `diskIdentifier` is populated by both macOS (system_profiler
  // `bsd_name`) and Linux. Match priority: serial number → whole-disk
  // identifier (partition suffix stripped on both sides) → emit-separate.
  // Pre-fix, the ad-hoc disk-name correlation here produced a double-entry
  // on Linux (linka repro): the same iPod rendered as both a mounted row
  // and a phantom "USB only" row claiming the device needed partitioning.
  const reconciled = reconcileIpodDiscovery(ipods, ipodRecognizedList);

  // Per-block-record matched USB classification, indexed by block-device
  // index for the readiness pipeline and the JSON envelope. Records without
  // a `block` side are USB-only iPods rendered separately.
  const matchedUsbByBlockIndex = new Map<number, IpodRecognized>();
  for (let i = 0; i < ipods.length; i++) {
    const record = reconciled.find((r) => r.block === ipods[i]);
    if (record?.usb) matchedUsbByBlockIndex.set(i, record.usb);
  }
  const usbOnlyIpods: IpodRecognized[] = reconciled
    .filter((r) => r.matchedBy === 'usb-only' && r.usb)
    .map((r) => r.usb!);

  function findMatchingUsbIpod(blockIndex: number): IpodRecognized | undefined {
    return matchedUsbByBlockIndex.get(blockIndex);
  }

  // Gather configured devices not found in the scan
  const detectedUuids = new Set(ipods.map((d) => d.volumeUuid?.toUpperCase()).filter(Boolean));
  const configuredDevices = findUndetectedDevices(detectedUuids, config.devices ?? {});

  // Run readiness pipeline on each iPod (only on supported platforms)
  const readinessResults: ReadinessResult[] = [];
  if (manager.isSupported) {
    for (let i = 0; i < ipods.length; i++) {
      const ipod = ipods[i]!;
      const matchedUsb = findMatchingUsbIpod(i);
      readinessResults.push(
        await checkReadiness({
          device: ipod,
          usbConnection: matchedUsb?.device,
          usbModel: matchedUsb?.model,
          // Thread the rejection reason so the readiness cascade returns
          // `level: 'unsupported'` for recognised-but-rejected iPods (touch,
          // iPhone, nano 6G/7G, …) rather than running the rest of the
          // pipeline against a device that will never mount in disk mode.
          // `classifyAsIpod` already produced the typed payload via
          // `lookupUnsupportedReadinessReason`, so it threads through verbatim.
          ...(matchedUsb && matchedUsb.supported === false && matchedUsb.unsupportedReason
            ? { unsupported: matchedUsb.unsupportedReason }
            : {}),
        })
      );
    }
  }

  // Handle unmounted devices: prompt or auto-mount
  if (manager.isSupported) {
    const { interpretError } = core;
    for (let i = 0; i < ipods.length; i++) {
      const ipod = ipods[i]!;
      if (ipod.isMounted) continue;

      const readiness = readinessResults[i];
      const mountStage = readiness?.stages.find((s) => s.stage === 'mount');
      if (!mountStage || mountStage.status !== 'fail') continue;
      if (mountStage.details?.isMounted !== false) continue;

      const label = ipod.volumeName || '(unnamed)';
      let shouldMount = false;

      if (scanOptions.mount) {
        // --mount flag: auto-mount
        shouldMount = true;
      } else if (process.stdout.isTTY && !globalOpts.json) {
        // Interactive TTY: prompt user
        shouldMount = await confirmFn(`${label} is unmounted. Mount now?`);
      }

      if (shouldMount) {
        try {
          const result = await manager.mount(ipod.identifier);
          if (result.success && result.mountPoint) {
            // Update the ipod entry with new mount info
            ipod.isMounted = true;
            (ipod as { mountPoint?: string }).mountPoint = result.mountPoint;
            // Re-run readiness to get full picture
            readinessResults[i] = await checkReadiness({ device: ipod });
            out.verbose1(`Mounted ${label} at ${result.mountPoint}`);
          } else if (result.requiresSudo) {
            const assessment = result.assessment;
            if (assessment?.iFlash.confirmed) {
              const lines = formatIFlashMountExplanation(assessment);
              for (const line of lines) {
                out.error(line);
              }
            } else {
              out.error(`Failed to mount ${label}: elevated privileges required.`);
            }
            out.newline();
            out.error(`Run:  ${bold('sudo')} podkit device scan --mount`);
          } else {
            const errMsg = result.error ?? 'Unknown mount error';
            const interpreted = interpretError(errMsg);
            out.error(`Failed to mount ${label}: ${interpreted.explanation}`);
          }
        } catch (err) {
          const interpreted = interpretError(err instanceof Error ? err : String(err));
          out.error(`Failed to mount ${label}: ${interpreted.explanation}`);
        }
      }
    }
  }

  const blockDevices: DeviceScanDeviceEntry[] = ipods.map((d, i) => {
    const readiness = readinessResults[i];
    const configuredAs = findConfiguredDeviceName(d, config.devices ?? {});
    const bestModel = readiness?.deviceModel ?? readiness?.usbModel;
    const matchedUsb = findMatchingUsbIpod(i);
    return {
      volumeName: d.volumeName,
      volumeUuid: d.volumeUuid,
      identifier: d.identifier,
      size: d.size,
      isMounted: d.isMounted,
      ...(d.mountPoint ? { mountPoint: d.mountPoint } : {}),
      ...(configuredAs ? { configuredAs } : {}),
      ...(bestModel ? { model: bestModel } : {}),
      ...(matchedUsb
        ? {
            usbDescriptor: {
              vendorId: matchedUsb.device.vendorId,
              productId: matchedUsb.device.productId,
              ...(matchedUsb.device.serialNumber
                ? { serialNumber: matchedUsb.device.serialNumber }
                : {}),
            },
          }
        : {}),
      ...(readiness
        ? {
            readiness: {
              level: readiness.level,
              stages: readiness.stages.map((s) => ({
                stage: s.stage,
                status: s.status,
                summary: s.summary,
                ...(s.details ? { details: s.details } : {}),
              })),
              ...(readiness.summary ? { summary: readiness.summary } : {}),
            },
          }
        : {}),
    };
  });

  // USB-only iPods: Apple-vendor USB descriptors with no joinable lsblk entry.
  // These appear for personas synthesised inside the Tier-3 VM that have no
  // block device (massStorageBackingFile: null) and for iPods in restore mode
  // (6G in particular). They share the same JSON shape as block-device-bound
  // entries, but with `usbOnly: true`, no `mountPoint`, and empty string
  // identifier/volumeUuid (size 0). The render layer continues to use the
  // separate `usbOnlyIpods` list — only the JSON envelope is unified here.
  const usbOnlyDevices: DeviceScanDeviceEntry[] = usbOnlyIpods.map((r) => {
    const usbReadiness = manager.isSupported ? createUsbOnlyReadinessResult(r) : undefined;
    const modelDisplayName = r.model?.displayName;
    return {
      volumeName: modelDisplayName ?? '',
      volumeUuid: '',
      identifier: '',
      size: 0,
      isMounted: false,
      usbOnly: true,
      usbDescriptor: {
        vendorId: r.device.vendorId,
        productId: r.device.productId,
        ...(r.device.serialNumber ? { serialNumber: r.device.serialNumber } : {}),
      },
      ...(r.model ? { model: r.model } : {}),
      ...(r.unsupportedReason ? { unsupportedReason: r.unsupportedReason } : {}),
      ...(usbReadiness
        ? {
            readiness: {
              level: usbReadiness.level,
              stages: usbReadiness.stages.map((s) => ({
                stage: s.stage,
                status: s.status,
                summary: s.summary,
                ...(s.details ? { details: s.details } : {}),
              })),
              ...(usbReadiness.summary ? { summary: usbReadiness.summary } : {}),
            },
          }
        : {}),
    };
  });

  // Vendor-recognised, no-preset devices (Sony Walkman, …) — rendered as
  // USB-only entries with an `unsupported` readiness level + canonical reason.
  const unsupportedDevices: DeviceScanDeviceEntry[] = unsupportedRecognizedList.map((r) => ({
    volumeName: r.family ?? '',
    volumeUuid: '',
    identifier: '',
    size: 0,
    isMounted: false,
    usbOnly: true,
    usbDescriptor: {
      vendorId: r.device.vendorId,
      productId: r.device.productId,
      ...(r.device.serialNumber ? { serialNumber: r.device.serialNumber } : {}),
    },
    unsupportedReason: { kind: 'unsupported-preset', headline: r.reason },
    readiness: {
      level: 'unsupported',
      stages: [
        {
          stage: 'usb',
          status: 'fail',
          summary: 'Device not supported',
          details: {
            vendorId: r.device.vendorId,
            productId: r.device.productId,
            unsupported: { kind: 'unsupported-preset', headline: r.reason },
          },
        },
      ],
    },
  }));

  const devices: DeviceScanDeviceEntry[] = [
    ...blockDevices,
    ...usbOnlyDevices,
    ...unsupportedDevices,
  ];

  const hasAnyDevices =
    ipods.length > 0 ||
    usbOnlyIpods.length > 0 ||
    massStorageList.length > 0 ||
    unsupportedRecognizedList.length > 0 ||
    configuredDevices.length > 0;

  // Handle --report flag: generate diagnostic report instead of normal output
  if (scanOptions.report) {
    // cliVersion comes from the runner argument; default 'unknown' if not supplied.
    const report = await generateDiagnosticReport(
      ipods,
      readinessResults,
      usbOnlyIpods.map((r) => ({
        modelName: r.model?.displayName,
        supported: r.supported,
        ...(r.unsupportedReason ? { unsupportedReason: r.unsupportedReason } : {}),
      })),
      massStorageList.map((r) => ({
        presetId: r.presetId,
        diskIdentifier: r.device.diskIdentifier,
      })),
      configuredDevices,
      config,
      cliVersion
    );
    out.stdout(redactPaths(report));
    return;
  }

  const ipodRows: DeviceScanIpodRow[] = ipods.map((device, i) => {
    const readiness = readinessResults[i];
    const matchedUsb = findMatchingUsbIpod(i);
    const configuredName = findConfiguredDeviceName(device, config.devices ?? {});
    return {
      device: {
        volumeName: device.volumeName,
        volumeUuid: device.volumeUuid,
        identifier: device.identifier,
        size: device.size,
        isMounted: device.isMounted,
        ...(device.mountPoint ? { mountPoint: device.mountPoint } : {}),
      },
      ...(readiness ? { readiness } : {}),
      ...(configuredName ? { configuredName } : {}),
      ...(matchedUsb?.model?.displayName
        ? { fallbackUsbModelDisplayName: matchedUsb.model.displayName }
        : {}),
    };
  });

  const renderInput: DeviceScanInput = {
    ipods: ipodRows,
    usbOnlyIpods,
    massStorageDevices: massStorageList,
    unsupportedDevices: unsupportedRecognizedList,
    configuredDevices,
    isSupportedPlatform: manager.isSupported,
    createUsbOnlyReadinessResult,
  };

  const writeRender = () => {
    for (const line of renderDeviceScan(renderInput)) {
      if (line === '') out.newline();
      else out.print(line);
    }
  };

  if (!hasAnyDevices) {
    out.result<DeviceScanOutput>(
      { success: true, devices: [], configuredDevices: [] },
      writeRender
    );
    return;
  }

  out.result<DeviceScanOutput>({ success: true, devices, configuredDevices }, writeRender);
}
