/**
 * `podkit device scan` — scan for connected devices.
 */
import { Command } from 'commander';
import { confirm } from '../../utils/confirm.js';
import { getContext } from '../../context.js';
import { runAction } from '../../errors.js';
import { loadCoreOrFail, type CoreLoaderDeps } from '../../handler-deps.js';
import { OutputContext, formatBytes, formatNumber, bold } from '../../output/index.js';
import type { DeviceConfig } from '../../config/index.js';
import type {
  DiscoveredDevice,
  DiscoveredDeviceIpod,
  PlatformDeviceInfo,
  ReadinessResult,
  ReadinessUnsupportedReason,
} from '@podkit/core';
import { STAGE_DISPLAY_NAMES } from '@podkit/core';
import { stageMarker, formatReadinessLevel } from '../readiness-display.js';
import {
  renderDeviceScan,
  type DeviceScanInput,
  type DiscoveredDeviceRow,
} from '../device-scan-render.js';
import { DeviceErrorCodes } from './error-codes.js';
import {
  findUndetectedDevices,
  findConfiguredDeviceName,
  redactPaths,
  formatIFlashMountExplanation,
} from './shared.js';
import type { DeviceScanOutput, DeviceScanSuccess } from './output-types.js';

type DeviceScanDeviceEntry = NonNullable<DeviceScanSuccess['devices']>[number];

/**
 * Generate a diagnostic report for troubleshooting.
 */
async function generateDiagnosticReport(
  ipods: Array<{
    volumeName: string;
    volumeUuid: string;
    identifier: string;
    isMounted: boolean;
    mountPoint?: string;
  }>,
  readinessResults: ReadinessResult[],
  usbOnlyIpods: Array<{
    modelName?: string;
    supported?: boolean;
    unsupportedReason?: ReadinessUnsupportedReason;
  }>,
  recognisedMassStorage: Array<{ presetId: string; diskIdentifier?: string }>,
  configuredDevices: Array<{ name: string; type: string; path?: string }>,
  config: { devices?: Record<string, DeviceConfig> },
  version: string
): Promise<string> {
  const { release } = await import('node:os');
  const lines: string[] = [];

  lines.push('podkit diagnostic report');
  lines.push('========================');
  lines.push('');

  // System info
  lines.push('System:');
  lines.push(`  podkit version: ${version}`);
  const platformName =
    process.platform === 'darwin'
      ? `darwin (macOS ${release()})`
      : `${process.platform} (${release()})`;
  lines.push(`  Platform: ${platformName}`);
  lines.push(`  Node.js: ${process.version}`);
  lines.push('');

  const hasAnyDevices =
    ipods.length > 0 ||
    usbOnlyIpods.length > 0 ||
    recognisedMassStorage.length > 0 ||
    configuredDevices.length > 0;

  if (!hasAnyDevices) {
    lines.push('No devices found.');
    lines.push('');
    lines.push('---');
    lines.push('Generated by podkit device scan --report');
    return lines.join('\n');
  }

  lines.push('Devices:');

  // iPods with readiness
  for (let i = 0; i < ipods.length; i++) {
    if (i > 0) lines.push('---');
    const device = ipods[i]!;
    const readiness = readinessResults[i];
    const label = device.volumeName || '(unnamed)';
    const identifier = device.identifier ? ` (${device.identifier})` : '';

    lines.push(`  iPod: ${label}${identifier}`);

    // Config relationship
    const configName = findConfiguredDeviceName(device, config.devices ?? {});
    if (configName) {
      lines.push(`  Configured as: ${configName}`);
    } else {
      lines.push('  Not configured');
    }

    if (readiness) {
      lines.push('');
      lines.push('  Readiness:');
      for (const stage of readiness.stages) {
        const marker = stageMarker(stage.status);
        const name = STAGE_DISPLAY_NAMES[stage.stage] || stage.stage;
        let line = `    ${marker} ${name}`;
        if (stage.summary) {
          line += ` — ${stage.summary}`;
        }
        lines.push(line);

        // Include error interpretation for failed stages
        if (stage.status === 'fail' && stage.details?.interpretation) {
          lines.push(`      ${stage.details.interpretation}`);
        }
      }

      lines.push('');

      // Summary line
      if (readiness.level === 'ready' && readiness.summary) {
        const trackStr = formatNumber(readiness.summary.trackCount);
        const parts = [`${trackStr} track${readiness.summary.trackCount === 1 ? '' : 's'}`];
        if (readiness.summary.freeBytes !== undefined) {
          parts.push(`${formatBytes(readiness.summary.freeBytes)} free`);
        }
        lines.push(`  Level: Ready — ${parts.join(', ')}`);
      } else {
        const cmdId = configName ?? device.mountPoint ?? label;
        lines.push(`  Level: ${formatReadinessLevel(readiness.level, cmdId)}`);
      }
    }

    lines.push('');
  }

  // USB-only iPods (recognised as iPods but with no mounted disk).
  for (const usbDevice of usbOnlyIpods) {
    lines.push('---');
    const label = usbDevice.modelName ?? 'Unknown iPod';
    lines.push(`  iPod: ${label} (USB only)`);
    if (!usbDevice.supported && usbDevice.unsupportedReason) {
      lines.push(`  ${usbDevice.unsupportedReason.headline}`);
    }
    lines.push('');
  }

  // Recognised mass-storage devices (Echo Mini etc.).
  for (const recognised of recognisedMassStorage) {
    lines.push('---');
    if (recognised.diskIdentifier) {
      lines.push(`  Mass-storage: ${recognised.presetId} — disk: ${recognised.diskIdentifier}`);
    } else {
      lines.push(`  Mass-storage: ${recognised.presetId} — no volume mounted`);
    }
    lines.push('');
  }

  // Configured devices not detected
  for (const cd of configuredDevices) {
    lines.push('---');
    const pathInfo = cd.path ? ` — ${cd.path}` : '';
    lines.push(`  ${cd.name} (${cd.type})${pathInfo} [not detected]`);
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by podkit device scan --report');
  return lines.join('\n');
}

interface DeviceScanOptions {
  mount?: boolean;
  report?: boolean;
}

/**
 * Dependency injection seam for `runDeviceScan`. Tests pass stubs to avoid
 * real USB walks and mount operations.
 */
export interface DeviceScanDeps extends CoreLoaderDeps {
  getDeviceManager?: () => import('@podkit/core').DeviceManager;
  confirm?: (msg: string) => Promise<boolean>;
  /**
   * Override for USB enumeration inside `discoverConnectedDevices`. Test seam:
   * allows injecting a fake USB device list without stubbing the full discovery
   * orchestrator.
   */
  enumerate?: () => Promise<import('@podkit/core').EnumeratedUsbDevice[]>;
  /**
   * Override for USB classification inside `discoverConnectedDevices`. Test seam:
   * allows injecting fake classified devices without stubbing the full discovery
   * orchestrator.
   */
  classify?: (
    devices: import('@podkit/core').EnumeratedUsbDevice[]
  ) => import('@podkit/core').ClassifiedUsbDevice[];
}

export const scanSubcommand = new Command('scan')
  .description('scan for connected devices')
  .option('--mount', 'automatically mount unmounted devices')
  .option('--report', 'output diagnostic report for troubleshooting')
  .action(async (scanOptions: DeviceScanOptions) => {
    const { globalOpts } = getContext();
    const out = OutputContext.fromGlobalOpts(globalOpts);
    const cliVersion = scanSubcommand.parent?.parent?.version() ?? 'unknown';
    await runAction(out, () => runDeviceScan(scanOptions, out, {}, cliVersion));
  });

export async function runDeviceScan(
  scanOptions: DeviceScanOptions,
  out: OutputContext,
  deps: DeviceScanDeps = {},
  cliVersion = 'unknown'
): Promise<void> {
  const { globalOpts, config } = getContext();
  const confirmFn = deps.confirm ?? confirm;

  const core = await loadCoreOrFail(deps, DeviceErrorCodes.CORE_LOAD_FAILED);
  const { checkReadiness, createUsbOnlyReadinessResult, discoverConnectedDevices } = core;
  const manager = (deps.getDeviceManager ?? core.getDeviceManager)();

  // Discover all connected devices — USB + block-device pipelines reconciled
  // into one record per physical device. Returns [] on unsupported platforms.
  // Test seams for `enumerate` and `classify` are threaded through so unit
  // tests can inject fake USB device lists without stubbing the full orchestrator.
  const discovered = await discoverConnectedDevices({
    deviceManager: manager,
    ...(deps.enumerate ? { enumerate: deps.enumerate } : {}),
    ...(deps.classify ? { classify: deps.classify } : {}),
  });

  // Extract the block-side iPod records for the mount-handling pipeline and
  // readiness checks. These are the iPods that have a block-device entry and
  // may need mounting or readiness evaluation.
  const blockIpods: Array<{ device: DiscoveredDeviceIpod; block: PlatformDeviceInfo }> = discovered
    .filter((d): d is DiscoveredDeviceIpod => d.kind === 'ipod' && d.matchedBy !== 'usb-only')
    .map((d) => ({ device: d, block: d.block! }));

  // Run readiness pipeline on each block-side iPod (only on supported platforms).
  // The readiness result array is indexed in parallel with blockIpods.
  const readinessResults: ReadinessResult[] = [];
  if (manager.isSupported) {
    for (const { device, block } of blockIpods) {
      const matchedUsb = device.usb;
      readinessResults.push(
        await checkReadiness({
          device: block,
          usbConnection: matchedUsb?.device,
          usbModel: matchedUsb?.model,
          // Thread the rejection reason so the readiness cascade returns
          // `level: 'unsupported'` for recognised-but-rejected iPods (touch,
          // iPhone, nano 6G/7G, …) rather than running the rest of the
          // pipeline against a device that will never mount in disk mode.
          // `classifyAsIpod` already produced the typed payload via
          // `lookupUnsupportedReadinessReason`, so it threads through verbatim.
          ...(matchedUsb && matchedUsb.supported === false && matchedUsb.unsupportedReason
            ? { unsupported: matchedUsb.unsupportedReason }
            : {}),
        })
      );
    }
  }

  // Handle unmounted devices: prompt or auto-mount
  if (manager.isSupported) {
    const { interpretError } = core;
    for (let i = 0; i < blockIpods.length; i++) {
      const { device: ipodDevice, block } = blockIpods[i]!;
      if (block.isMounted) continue;

      const readiness = readinessResults[i];
      const mountStage = readiness?.stages.find((s) => s.stage === 'mount');
      if (!mountStage || mountStage.status !== 'fail') continue;
      if (mountStage.details?.isMounted !== false) continue;

      const label = block.volumeName || '(unnamed)';
      let shouldMount = false;

      if (scanOptions.mount) {
        // --mount flag: auto-mount
        shouldMount = true;
      } else if (process.stdout.isTTY && !globalOpts.json) {
        // Interactive TTY: prompt user
        shouldMount = await confirmFn(`${label} is unmounted. Mount now?`);
      }

      if (shouldMount) {
        try {
          const result = await manager.mount(block.identifier);
          if (result.success && result.mountPoint) {
            // Update the block entry with new mount info. The discriminated
            // mount-state union forbids partial mutation — build a new
            // record with `isMounted: true` + `mountPoint` and replace the
            // slot.
            // Spread of an unmounted `block` carries `isMounted: false` in
            // its inferred type; rebuild from identity + storage + usb so
            // the discriminated mount-state union narrows correctly.
            const { identifier, volumeName, volumeUuid, storage, usb, mediaType } = block;
            const mounted: PlatformDeviceInfo = {
              identifier,
              volumeName,
              volumeUuid,
              storage,
              isMounted: true,
              mountPoint: result.mountPoint,
              ...(usb ? { usb } : {}),
              ...(mediaType ? { mediaType } : {}),
            };
            blockIpods[i] = { device: ipodDevice, block: mounted };
            // Re-run readiness to get full picture
            readinessResults[i] = await checkReadiness({ device: mounted });
            out.verbose1(`Mounted ${label} at ${result.mountPoint}`);
          } else if (result.requiresSudo) {
            const assessment = result.assessment;
            if (assessment?.iFlash.confirmed) {
              const lines = formatIFlashMountExplanation(assessment);
              for (const line of lines) {
                out.error(line);
              }
            } else {
              out.error(`Failed to mount ${label}: elevated privileges required.`);
            }
            out.newline();
            out.error(`Run:  ${bold('sudo')} podkit device scan --mount`);
          } else {
            const errMsg = result.error ?? 'Unknown mount error';
            const interpreted = interpretError(errMsg);
            out.error(`Failed to mount ${label}: ${interpreted.explanation}`);
          }
        } catch (err) {
          const interpreted = interpretError(err instanceof Error ? err : String(err));
          out.error(`Failed to mount ${label}: ${interpreted.explanation}`);
        }
      }
    }
  }

  // Rebuild the discovered list with updated block records (post-mount).
  // We replace DiscoveredDeviceIpod entries that had their block updated.
  const discoveredWithMounts: DiscoveredDevice[] = discovered.map((d) => {
    if (d.kind !== 'ipod' || d.matchedBy === 'usb-only') return d;
    const idx = blockIpods.findIndex((bi) => bi.block.identifier === d.block?.identifier);
    if (idx === -1) return d;
    return { ...d, block: blockIpods[idx]!.block } as DiscoveredDeviceIpod;
  });

  // Gather configured devices not found in the scan
  const detectedUuids = new Set(
    blockIpods.map((bi) => bi.block.volumeUuid?.toUpperCase()).filter(Boolean) as string[]
  );
  const configuredDevices = findUndetectedDevices(detectedUuids, config.devices ?? {});

  // Build the JSON output envelope (unchanged shape from before).
  // Block-side iPods with readiness data.
  const blockDevices: DeviceScanDeviceEntry[] = blockIpods.map(({ device, block }, i) => {
    const readiness = readinessResults[i];
    const configuredAs = findConfiguredDeviceName(block, config.devices ?? {});
    const bestModel = readiness?.deviceModel ?? readiness?.usbModel;
    const matchedUsb = device.usb;
    return {
      volumeName: block.volumeName,
      volumeUuid: block.volumeUuid,
      identifier: block.identifier,
      size: block.storage.sizeBytes,
      isMounted: block.isMounted,
      ...(block.isMounted ? { mountPoint: block.mountPoint } : {}),
      ...(configuredAs ? { configuredAs } : {}),
      ...(bestModel ? { model: bestModel } : {}),
      ...(matchedUsb
        ? {
            usbDescriptor: {
              vendorId: matchedUsb.device.vendorId,
              productId: matchedUsb.device.productId,
              ...(matchedUsb.device.serialNumber
                ? { serialNumber: matchedUsb.device.serialNumber }
                : {}),
            },
          }
        : {}),
      ...(readiness
        ? {
            readiness: {
              level: readiness.level,
              stages: readiness.stages.map((s) => ({
                stage: s.stage,
                status: s.status,
                summary: s.summary,
                ...(s.details ? { details: s.details } : {}),
              })),
              ...(readiness.summary ? { summary: readiness.summary } : {}),
            },
          }
        : {}),
    };
  });

  // USB-only iPods: Apple-vendor USB descriptors with no joinable block entry.
  const usbOnlyIpodDevices = discoveredWithMounts.filter(
    (d): d is DiscoveredDeviceIpod => d.kind === 'ipod' && d.matchedBy === 'usb-only'
  );
  const usbOnlyDevices: DeviceScanDeviceEntry[] = usbOnlyIpodDevices.map((r) => {
    const usbReadiness =
      manager.isSupported && r.usb ? createUsbOnlyReadinessResult(r.usb) : undefined;
    const modelDisplayName = r.usb?.model?.displayName;
    return {
      volumeName: modelDisplayName ?? '',
      volumeUuid: '',
      identifier: '',
      size: 0,
      isMounted: false,
      usbOnly: true,
      ...(r.usb
        ? {
            usbDescriptor: {
              vendorId: r.usb.device.vendorId,
              productId: r.usb.device.productId,
              ...(r.usb.device.serialNumber ? { serialNumber: r.usb.device.serialNumber } : {}),
            },
          }
        : {}),
      ...(r.usb?.model ? { model: r.usb.model } : {}),
      ...(r.usb?.unsupportedReason ? { unsupportedReason: r.usb.unsupportedReason } : {}),
      ...(usbReadiness
        ? {
            readiness: {
              level: usbReadiness.level,
              stages: usbReadiness.stages.map((s) => ({
                stage: s.stage,
                status: s.status,
                summary: s.summary,
                ...(s.details ? { details: s.details } : {}),
              })),
              ...(usbReadiness.summary ? { summary: usbReadiness.summary } : {}),
            },
          }
        : {}),
    };
  });

  // Vendor-recognised, no-preset devices (Sony Walkman, …) — rendered as
  // USB-only entries with an `unsupported` readiness level + canonical reason.
  const unsupportedDevices: DeviceScanDeviceEntry[] = discoveredWithMounts
    .filter(
      (d): d is import('@podkit/core').DiscoveredDeviceUnsupported => d.kind === 'unsupported'
    )
    .map((r) => ({
      volumeName: r.usb.family ?? '',
      volumeUuid: '',
      identifier: '',
      size: 0,
      isMounted: false,
      usbOnly: true,
      usbDescriptor: {
        vendorId: r.usb.device.vendorId,
        productId: r.usb.device.productId,
        ...(r.usb.device.serialNumber ? { serialNumber: r.usb.device.serialNumber } : {}),
      },
      unsupportedReason: { kind: 'unsupported-preset', headline: r.usb.reason },
      readiness: {
        level: 'unsupported',
        stages: [
          {
            stage: 'usb',
            status: 'fail',
            summary: 'Device not supported',
            details: {
              vendorId: r.usb.device.vendorId,
              productId: r.usb.device.productId,
              unsupported: { kind: 'unsupported-preset', headline: r.usb.reason },
            },
          },
        ],
      },
    }));

  const devices: DeviceScanDeviceEntry[] = [
    ...blockDevices,
    ...usbOnlyDevices,
    ...unsupportedDevices,
  ];

  const massStorageDevices = discoveredWithMounts.filter(
    (d): d is import('@podkit/core').DiscoveredDeviceMassStorage => d.kind === 'mass-storage'
  );

  const hasAnyDevices = discovered.length > 0 || configuredDevices.length > 0;

  // Handle --report flag: generate diagnostic report instead of normal output
  if (scanOptions.report) {
    // Derive the flat lists that generateDiagnosticReport expects from discoveredWithMounts.
    const reportIpods = blockIpods.map(({ block }) => ({
      volumeName: block.volumeName,
      volumeUuid: block.volumeUuid,
      identifier: block.identifier,
      isMounted: block.isMounted,
      ...(block.isMounted ? { mountPoint: block.mountPoint } : {}),
    }));

    const reportUsbOnlyIpods = usbOnlyIpodDevices.map((r) => ({
      modelName: r.usb?.model?.displayName,
      supported: r.usb?.supported,
      ...(r.usb?.unsupportedReason ? { unsupportedReason: r.usb.unsupportedReason } : {}),
    }));

    const reportMassStorage = massStorageDevices
      .filter((d) => d.usb !== undefined)
      .map((d) => ({
        presetId: d.usb!.presetId,
        diskIdentifier: d.usb!.device.diskIdentifier,
      }));

    const report = await generateDiagnosticReport(
      reportIpods,
      readinessResults,
      reportUsbOnlyIpods,
      reportMassStorage,
      configuredDevices,
      config,
      cliVersion
    );
    out.stdout(redactPaths(report));
    return;
  }

  // Build render rows — one DiscoveredDeviceRow per discovered device,
  // with readiness pre-computed by the caller (pure renderer has no async).
  const discoveredRows: DiscoveredDeviceRow[] = discoveredWithMounts.map((d) => {
    if (d.kind === 'ipod' && d.matchedBy !== 'usb-only') {
      // Block-side iPod: look up readiness by block identifier.
      const idx = blockIpods.findIndex((bi) => bi.block.identifier === d.block?.identifier);
      const readiness = idx !== -1 ? readinessResults[idx] : undefined;
      const configuredName = d.block
        ? findConfiguredDeviceName(d.block, config.devices ?? {})
        : undefined;
      return {
        device: d,
        ...(readiness ? { readiness } : {}),
        ...(configuredName ? { configuredName } : {}),
      };
    }

    if (d.kind === 'ipod' && d.matchedBy === 'usb-only') {
      // USB-only iPod: compute synthetic readiness result from USB classification.
      const readiness =
        manager.isSupported && d.usb ? createUsbOnlyReadinessResult(d.usb) : undefined;
      return {
        device: d,
        ...(readiness ? { readiness } : {}),
      };
    }

    // Mass-storage and unsupported: no readiness, no configured name.
    return { device: d };
  });

  const renderInput: DeviceScanInput = {
    discovered: discoveredRows,
    configuredDevices,
    isSupportedPlatform: manager.isSupported,
  };

  const writeRender = () => {
    for (const line of renderDeviceScan(renderInput)) {
      if (line === '') out.newline();
      else out.print(line);
    }
  };

  if (!hasAnyDevices) {
    out.result<DeviceScanOutput>(
      { success: true, devices: [], configuredDevices: [] },
      writeRender
    );
    return;
  }

  out.result<DeviceScanOutput>({ success: true, devices, configuredDevices }, writeRender);
}
