name: Test Daemon Build

on:
  workflow_dispatch:
  push:
    branches:
      - ci/build-daemon-binary

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-platform.yml
    with:
      upload-artifacts: true

  docker:
    needs: build
    if: needs.build.result == 'success'
    uses: ./.github/workflows/docker.yml
    with:
      version: 0.0.0-test
      push: false
